spring:
  main:
    banner-mode: 'off'
  application:
    name: bank-atm
  data:
    mongodb:
      uri: mongodb+srv://atm:atm@cluster0.ml6pw.mongodb.net/atm?retryWrites=true&w=majority
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    http2:
      enabled: true
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN

application:
  atm-info-url: https://www.vtb.ru/nsp.xml
  chunk-size: 200

springfox:
  documentation:
    open-api:
      v3:
        path: /api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html